// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: memory/v1/memory.proto

package memoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MemoryScope narrows where a search reads from. Multiple scopes can be
// OR'd together by repeating the field in the request.
type MemoryScope int32

const (
	MemoryScope_MEMORY_SCOPE_UNSPECIFIED MemoryScope = 0
	MemoryScope_MEMORY_SCOPE_USER        MemoryScope = 1
	MemoryScope_MEMORY_SCOPE_SESSION     MemoryScope = 2
	MemoryScope_MEMORY_SCOPE_TENANT      MemoryScope = 3
)

// Enum value maps for MemoryScope.
var (
	MemoryScope_name = map[int32]string{
		0: "MEMORY_SCOPE_UNSPECIFIED",
		1: "MEMORY_SCOPE_USER",
		2: "MEMORY_SCOPE_SESSION",
		3: "MEMORY_SCOPE_TENANT",
	}
	MemoryScope_value = map[string]int32{
		"MEMORY_SCOPE_UNSPECIFIED": 0,
		"MEMORY_SCOPE_USER":        1,
		"MEMORY_SCOPE_SESSION":     2,
		"MEMORY_SCOPE_TENANT":      3,
	}
)

func (x MemoryScope) Enum() *MemoryScope {
	p := new(MemoryScope)
	*p = x
	return p
}

func (x MemoryScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemoryScope) Descriptor() protoreflect.EnumDescriptor {
	return file_memory_v1_memory_proto_enumTypes[0].Descriptor()
}

func (MemoryScope) Type() protoreflect.EnumType {
	return &file_memory_v1_memory_proto_enumTypes[0]
}

func (x MemoryScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemoryScope.Descriptor instead.
func (MemoryScope) EnumDescriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{0}
}

type MemoryRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix epoch seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryRecord) Reset() {
	*x = MemoryRecord{}
	mi := &file_memory_v1_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryRecord) ProtoMessage() {}

func (x *MemoryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryRecord.ProtoReflect.Descriptor instead.
func (*MemoryRecord) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{0}
}

func (x *MemoryRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryRecord) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *MemoryRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MemoryRecord) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MemoryRecord) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryRecord) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MemoryRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type WriteMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteMemoryRequest) Reset() {
	*x = WriteMemoryRequest{}
	mi := &file_memory_v1_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteMemoryRequest) ProtoMessage() {}

func (x *WriteMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteMemoryRequest.ProtoReflect.Descriptor instead.
func (*WriteMemoryRequest) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{1}
}

func (x *WriteMemoryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *WriteMemoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WriteMemoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WriteMemoryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WriteMemoryRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type WriteMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteMemoryResponse) Reset() {
	*x = WriteMemoryResponse{}
	mi := &file_memory_v1_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteMemoryResponse) ProtoMessage() {}

func (x *WriteMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteMemoryResponse.ProtoReflect.Descriptor instead.
func (*WriteMemoryResponse) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{2}
}

func (x *WriteMemoryResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WriteMemoryResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type SearchMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Query         string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,5,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Scopes        []MemoryScope          `protobuf:"varint,6,rep,packed,name=scopes,proto3,enum=memory.v1.MemoryScope" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMemoryRequest) Reset() {
	*x = SearchMemoryRequest{}
	mi := &file_memory_v1_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMemoryRequest) ProtoMessage() {}

func (x *SearchMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMemoryRequest.ProtoReflect.Descriptor instead.
func (*SearchMemoryRequest) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{3}
}

func (x *SearchMemoryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SearchMemoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchMemoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SearchMemoryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchMemoryRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchMemoryRequest) GetScopes() []MemoryScope {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type SearchMemoryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *MemoryRecord          `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMemoryResult) Reset() {
	*x = SearchMemoryResult{}
	mi := &file_memory_v1_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMemoryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMemoryResult) ProtoMessage() {}

func (x *SearchMemoryResult) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMemoryResult.ProtoReflect.Descriptor instead.
func (*SearchMemoryResult) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{4}
}

func (x *SearchMemoryResult) GetRecord() *MemoryRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *SearchMemoryResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SearchMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchMemoryResult  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMemoryResponse) Reset() {
	*x = SearchMemoryResponse{}
	mi := &file_memory_v1_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMemoryResponse) ProtoMessage() {}

func (x *SearchMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMemoryResponse.ProtoReflect.Descriptor instead.
func (*SearchMemoryResponse) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{5}
}

func (x *SearchMemoryResponse) GetResults() []*SearchMemoryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type DeleteMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoryRequest) Reset() {
	*x = DeleteMemoryRequest{}
	mi := &file_memory_v1_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoryRequest) ProtoMessage() {}

func (x *DeleteMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemoryRequest) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteMemoryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteMemoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoryResponse) Reset() {
	*x = DeleteMemoryResponse{}
	mi := &file_memory_v1_memory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoryResponse) ProtoMessage() {}

func (x *DeleteMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteMemoryResponse) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMemoryResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_memory_v1_memory_proto protoreflect.FileDescriptor

const file_memory_v1_memory_proto_rawDesc = "" +
	"\n" +
	"\x16memory/v1/memory.proto\x12\tmemory.v1\"\xac\x02\n" +
	"\fMemoryRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12A\n" +
	"\bmetadata\x18\x06 \x03(\v2%.memory.v1.MemoryRecord.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x02\n" +
	"\x12WriteMemoryRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12G\n" +
	"\bmetadata\x18\x05 \x03(\v2+.memory.v1.WriteMemoryRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x13WriteMemoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\"\xc5\x01\n" +
	"\x13SearchMemoryRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x05 \x01(\x05R\x04topK\x12.\n" +
	"\x06scopes\x18\x06 \x03(\x0e2\x16.memory.v1.MemoryScopeR\x06scopes\"[\n" +
	"\x12SearchMemoryResult\x12/\n" +
	"\x06record\x18\x01 \x01(\v2\x17.memory.v1.MemoryRecordR\x06record\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\"O\n" +
	"\x14SearchMemoryResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.memory.v1.SearchMemoryResultR\aresults\"B\n" +
	"\x13DeleteMemoryRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"0\n" +
	"\x14DeleteMemoryResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted*u\n" +
	"\vMemoryScope\x12\x1c\n" +
	"\x18MEMORY_SCOPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MEMORY_SCOPE_USER\x10\x01\x12\x18\n" +
	"\x14MEMORY_SCOPE_SESSION\x10\x02\x12\x17\n" +
	"\x13MEMORY_SCOPE_TENANT\x10\x032\xff\x01\n" +
	"\rMemoryService\x12L\n" +
	"\vWriteMemory\x12\x1d.memory.v1.WriteMemoryRequest\x1a\x1e.memory.v1.WriteMemoryResponse\x12O\n" +
	"\fSearchMemory\x12\x1e.memory.v1.SearchMemoryRequest\x1a\x1f.memory.v1.SearchMemoryResponse\x12O\n" +
	"\fDeleteMemory\x12\x1e.memory.v1.DeleteMemoryRequest\x1a\x1f.memory.v1.DeleteMemoryResponseB@Z>github.com/kennguy3n/hunting-fishball/proto/memory/v1;memoryv1b\x06proto3"

var (
	file_memory_v1_memory_proto_rawDescOnce sync.Once
	file_memory_v1_memory_proto_rawDescData []byte
)

func file_memory_v1_memory_proto_rawDescGZIP() []byte {
	file_memory_v1_memory_proto_rawDescOnce.Do(func() {
		file_memory_v1_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_memory_v1_memory_proto_rawDesc), len(file_memory_v1_memory_proto_rawDesc)))
	})
	return file_memory_v1_memory_proto_rawDescData
}

var file_memory_v1_memory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_memory_v1_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_memory_v1_memory_proto_goTypes = []any{
	(MemoryScope)(0),             // 0: memory.v1.MemoryScope
	(*MemoryRecord)(nil),         // 1: memory.v1.MemoryRecord
	(*WriteMemoryRequest)(nil),   // 2: memory.v1.WriteMemoryRequest
	(*WriteMemoryResponse)(nil),  // 3: memory.v1.WriteMemoryResponse
	(*SearchMemoryRequest)(nil),  // 4: memory.v1.SearchMemoryRequest
	(*SearchMemoryResult)(nil),   // 5: memory.v1.SearchMemoryResult
	(*SearchMemoryResponse)(nil), // 6: memory.v1.SearchMemoryResponse
	(*DeleteMemoryRequest)(nil),  // 7: memory.v1.DeleteMemoryRequest
	(*DeleteMemoryResponse)(nil), // 8: memory.v1.DeleteMemoryResponse
	nil,                          // 9: memory.v1.MemoryRecord.MetadataEntry
	nil,                          // 10: memory.v1.WriteMemoryRequest.MetadataEntry
}
var file_memory_v1_memory_proto_depIdxs = []int32{
	9,  // 0: memory.v1.MemoryRecord.metadata:type_name -> memory.v1.MemoryRecord.MetadataEntry
	10, // 1: memory.v1.WriteMemoryRequest.metadata:type_name -> memory.v1.WriteMemoryRequest.MetadataEntry
	0,  // 2: memory.v1.SearchMemoryRequest.scopes:type_name -> memory.v1.MemoryScope
	1,  // 3: memory.v1.SearchMemoryResult.record:type_name -> memory.v1.MemoryRecord
	5,  // 4: memory.v1.SearchMemoryResponse.results:type_name -> memory.v1.SearchMemoryResult
	2,  // 5: memory.v1.MemoryService.WriteMemory:input_type -> memory.v1.WriteMemoryRequest
	4,  // 6: memory.v1.MemoryService.SearchMemory:input_type -> memory.v1.SearchMemoryRequest
	7,  // 7: memory.v1.MemoryService.DeleteMemory:input_type -> memory.v1.DeleteMemoryRequest
	3,  // 8: memory.v1.MemoryService.WriteMemory:output_type -> memory.v1.WriteMemoryResponse
	6,  // 9: memory.v1.MemoryService.SearchMemory:output_type -> memory.v1.SearchMemoryResponse
	8,  // 10: memory.v1.MemoryService.DeleteMemory:output_type -> memory.v1.DeleteMemoryResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_memory_v1_memory_proto_init() }
func file_memory_v1_memory_proto_init() {
	if File_memory_v1_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_memory_v1_memory_proto_rawDesc), len(file_memory_v1_memory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_memory_v1_memory_proto_goTypes,
		DependencyIndexes: file_memory_v1_memory_proto_depIdxs,
		EnumInfos:         file_memory_v1_memory_proto_enumTypes,
		MessageInfos:      file_memory_v1_memory_proto_msgTypes,
	}.Build()
	File_memory_v1_memory_proto = out.File
	file_memory_v1_memory_proto_goTypes = nil
	file_memory_v1_memory_proto_depIdxs = nil
}
