// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: reranker/v1/reranker.proto

package rerankerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Candidate is a single rerank-input document. The connector layer
// surfaces chunk_id (stable per-tenant) and text (the chunk body).
// score carries the upstream fusion score so the sidecar can
// stabilize ties using the existing ranking when the cross-encoder
// is uncertain.
type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_reranker_v1_reranker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_reranker_v1_reranker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_reranker_v1_reranker_proto_rawDescGZIP(), []int{0}
}

func (x *Candidate) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *Candidate) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Candidate) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RerankRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TenantId   string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Query      string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Candidates []*Candidate           `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`
	// model_id selects a specific cross-encoder. Empty means "use
	// the sidecar default", which the Python process resolves from
	// its own config map.
	ModelId string `protobuf:"bytes,4,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// top_k optionally truncates the response. Zero means "return
	// every candidate".
	TopK          int32 `protobuf:"varint,5,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankRequest) Reset() {
	*x = RerankRequest{}
	mi := &file_reranker_v1_reranker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankRequest) ProtoMessage() {}

func (x *RerankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reranker_v1_reranker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankRequest.ProtoReflect.Descriptor instead.
func (*RerankRequest) Descriptor() ([]byte, []int) {
	return file_reranker_v1_reranker_proto_rawDescGZIP(), []int{1}
}

func (x *RerankRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RerankRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RerankRequest) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *RerankRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *RerankRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

// ScoredCandidate carries the post-rerank cross-encoder score.
// Callers replace the existing Match.Score field with this value.
type ScoredCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoredCandidate) Reset() {
	*x = ScoredCandidate{}
	mi := &file_reranker_v1_reranker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredCandidate) ProtoMessage() {}

func (x *ScoredCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_reranker_v1_reranker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredCandidate.ProtoReflect.Descriptor instead.
func (*ScoredCandidate) Descriptor() ([]byte, []int) {
	return file_reranker_v1_reranker_proto_rawDescGZIP(), []int{2}
}

func (x *ScoredCandidate) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ScoredCandidate) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RerankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scored        []*ScoredCandidate     `protobuf:"bytes,1,rep,name=scored,proto3" json:"scored,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankResponse) Reset() {
	*x = RerankResponse{}
	mi := &file_reranker_v1_reranker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankResponse) ProtoMessage() {}

func (x *RerankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reranker_v1_reranker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankResponse.ProtoReflect.Descriptor instead.
func (*RerankResponse) Descriptor() ([]byte, []int) {
	return file_reranker_v1_reranker_proto_rawDescGZIP(), []int{3}
}

func (x *RerankResponse) GetScored() []*ScoredCandidate {
	if x != nil {
		return x.Scored
	}
	return nil
}

func (x *RerankResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

var File_reranker_v1_reranker_proto protoreflect.FileDescriptor

const file_reranker_v1_reranker_proto_rawDesc = "" +
	"\n" +
	"\x1areranker/v1/reranker.proto\x12\vreranker.v1\"P\n" +
	"\tCandidate\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\"\xaa\x01\n" +
	"\rRerankRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x126\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v2\x16.reranker.v1.CandidateR\n" +
	"candidates\x12\x19\n" +
	"\bmodel_id\x18\x04 \x01(\tR\amodelId\x12\x13\n" +
	"\x05top_k\x18\x05 \x01(\x05R\x04topK\"B\n" +
	"\x0fScoredCandidate\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\"a\n" +
	"\x0eRerankResponse\x124\n" +
	"\x06scored\x18\x01 \x03(\v2\x1c.reranker.v1.ScoredCandidateR\x06scored\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId2T\n" +
	"\x0fRerankerService\x12A\n" +
	"\x06Rerank\x12\x1a.reranker.v1.RerankRequest\x1a\x1b.reranker.v1.RerankResponseBDZBgithub.com/kennguy3n/hunting-fishball/proto/reranker/v1;rerankerv1b\x06proto3"

var (
	file_reranker_v1_reranker_proto_rawDescOnce sync.Once
	file_reranker_v1_reranker_proto_rawDescData []byte
)

func file_reranker_v1_reranker_proto_rawDescGZIP() []byte {
	file_reranker_v1_reranker_proto_rawDescOnce.Do(func() {
		file_reranker_v1_reranker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reranker_v1_reranker_proto_rawDesc), len(file_reranker_v1_reranker_proto_rawDesc)))
	})
	return file_reranker_v1_reranker_proto_rawDescData
}

var file_reranker_v1_reranker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_reranker_v1_reranker_proto_goTypes = []any{
	(*Candidate)(nil),       // 0: reranker.v1.Candidate
	(*RerankRequest)(nil),   // 1: reranker.v1.RerankRequest
	(*ScoredCandidate)(nil), // 2: reranker.v1.ScoredCandidate
	(*RerankResponse)(nil),  // 3: reranker.v1.RerankResponse
}
var file_reranker_v1_reranker_proto_depIdxs = []int32{
	0, // 0: reranker.v1.RerankRequest.candidates:type_name -> reranker.v1.Candidate
	2, // 1: reranker.v1.RerankResponse.scored:type_name -> reranker.v1.ScoredCandidate
	1, // 2: reranker.v1.RerankerService.Rerank:input_type -> reranker.v1.RerankRequest
	3, // 3: reranker.v1.RerankerService.Rerank:output_type -> reranker.v1.RerankResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_reranker_v1_reranker_proto_init() }
func file_reranker_v1_reranker_proto_init() {
	if File_reranker_v1_reranker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reranker_v1_reranker_proto_rawDesc), len(file_reranker_v1_reranker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reranker_v1_reranker_proto_goTypes,
		DependencyIndexes: file_reranker_v1_reranker_proto_depIdxs,
		MessageInfos:      file_reranker_v1_reranker_proto_msgTypes,
	}.Build()
	File_reranker_v1_reranker_proto = out.File
	file_reranker_v1_reranker_proto_goTypes = nil
	file_reranker_v1_reranker_proto_depIdxs = nil
}
