// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: reranker/v1/reranker.proto

package rerankerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RerankerService_Rerank_FullMethodName = "/reranker.v1.RerankerService/Rerank"
)

// RerankerServiceClient is the client API for RerankerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RerankerService wraps the Python cross-encoder reranker sidecar.
// The Go retrieval handler calls Rerank after the merger fuses the
// four streams via RRF, when CONTEXT_ENGINE_CROSS_ENCODER_ENABLED
// is set. Gated callers fall back to the in-process LinearReranker.
type RerankerServiceClient interface {
	Rerank(ctx context.Context, in *RerankRequest, opts ...grpc.CallOption) (*RerankResponse, error)
}

type rerankerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRerankerServiceClient(cc grpc.ClientConnInterface) RerankerServiceClient {
	return &rerankerServiceClient{cc}
}

func (c *rerankerServiceClient) Rerank(ctx context.Context, in *RerankRequest, opts ...grpc.CallOption) (*RerankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RerankResponse)
	err := c.cc.Invoke(ctx, RerankerService_Rerank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RerankerServiceServer is the server API for RerankerService service.
// All implementations must embed UnimplementedRerankerServiceServer
// for forward compatibility.
//
// RerankerService wraps the Python cross-encoder reranker sidecar.
// The Go retrieval handler calls Rerank after the merger fuses the
// four streams via RRF, when CONTEXT_ENGINE_CROSS_ENCODER_ENABLED
// is set. Gated callers fall back to the in-process LinearReranker.
type RerankerServiceServer interface {
	Rerank(context.Context, *RerankRequest) (*RerankResponse, error)
	mustEmbedUnimplementedRerankerServiceServer()
}

// UnimplementedRerankerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRerankerServiceServer struct{}

func (UnimplementedRerankerServiceServer) Rerank(context.Context, *RerankRequest) (*RerankResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rerank not implemented")
}
func (UnimplementedRerankerServiceServer) mustEmbedUnimplementedRerankerServiceServer() {}
func (UnimplementedRerankerServiceServer) testEmbeddedByValue()                         {}

// UnsafeRerankerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RerankerServiceServer will
// result in compilation errors.
type UnsafeRerankerServiceServer interface {
	mustEmbedUnimplementedRerankerServiceServer()
}

func RegisterRerankerServiceServer(s grpc.ServiceRegistrar, srv RerankerServiceServer) {
	// If the following call panics, it indicates UnimplementedRerankerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RerankerService_ServiceDesc, srv)
}

func _RerankerService_Rerank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RerankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RerankerServiceServer).Rerank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RerankerService_Rerank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RerankerServiceServer).Rerank(ctx, req.(*RerankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RerankerService_ServiceDesc is the grpc.ServiceDesc for RerankerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RerankerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reranker.v1.RerankerService",
	HandlerType: (*RerankerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Rerank",
			Handler:    _RerankerService_Rerank_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reranker/v1/reranker.proto",
}
