// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: docling/v1/docling.proto

package doclingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BlockType classifies a parsed block. Mirrors Docling's coarse block
// taxonomy.
type BlockType int32

const (
	BlockType_BLOCK_TYPE_UNSPECIFIED BlockType = 0
	BlockType_BLOCK_TYPE_PARAGRAPH   BlockType = 1
	BlockType_BLOCK_TYPE_HEADING     BlockType = 2
	BlockType_BLOCK_TYPE_LIST_ITEM   BlockType = 3
	BlockType_BLOCK_TYPE_TABLE       BlockType = 4
	BlockType_BLOCK_TYPE_FIGURE      BlockType = 5
	BlockType_BLOCK_TYPE_CAPTION     BlockType = 6
	BlockType_BLOCK_TYPE_CODE        BlockType = 7
	BlockType_BLOCK_TYPE_FOOTNOTE    BlockType = 8
)

// Enum value maps for BlockType.
var (
	BlockType_name = map[int32]string{
		0: "BLOCK_TYPE_UNSPECIFIED",
		1: "BLOCK_TYPE_PARAGRAPH",
		2: "BLOCK_TYPE_HEADING",
		3: "BLOCK_TYPE_LIST_ITEM",
		4: "BLOCK_TYPE_TABLE",
		5: "BLOCK_TYPE_FIGURE",
		6: "BLOCK_TYPE_CAPTION",
		7: "BLOCK_TYPE_CODE",
		8: "BLOCK_TYPE_FOOTNOTE",
	}
	BlockType_value = map[string]int32{
		"BLOCK_TYPE_UNSPECIFIED": 0,
		"BLOCK_TYPE_PARAGRAPH":   1,
		"BLOCK_TYPE_HEADING":     2,
		"BLOCK_TYPE_LIST_ITEM":   3,
		"BLOCK_TYPE_TABLE":       4,
		"BLOCK_TYPE_FIGURE":      5,
		"BLOCK_TYPE_CAPTION":     6,
		"BLOCK_TYPE_CODE":        7,
		"BLOCK_TYPE_FOOTNOTE":    8,
	}
)

func (x BlockType) Enum() *BlockType {
	p := new(BlockType)
	*p = x
	return p
}

func (x BlockType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlockType) Descriptor() protoreflect.EnumDescriptor {
	return file_docling_v1_docling_proto_enumTypes[0].Descriptor()
}

func (BlockType) Type() protoreflect.EnumType {
	return &file_docling_v1_docling_proto_enumTypes[0]
}

func (x BlockType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlockType.Descriptor instead.
func (BlockType) EnumDescriptor() ([]byte, []int) {
	return file_docling_v1_docling_proto_rawDescGZIP(), []int{0}
}

// TableCell is a single cell inside a parsed table.
type TableCell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowIndex      int32                  `protobuf:"varint,1,opt,name=row_index,json=rowIndex,proto3" json:"row_index,omitempty"`
	ColIndex      int32                  `protobuf:"varint,2,opt,name=col_index,json=colIndex,proto3" json:"col_index,omitempty"`
	RowSpan       int32                  `protobuf:"varint,3,opt,name=row_span,json=rowSpan,proto3" json:"row_span,omitempty"`
	ColSpan       int32                  `protobuf:"varint,4,opt,name=col_span,json=colSpan,proto3" json:"col_span,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	IsHeader      bool                   `protobuf:"varint,6,opt,name=is_header,json=isHeader,proto3" json:"is_header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableCell) Reset() {
	*x = TableCell{}
	mi := &file_docling_v1_docling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableCell) ProtoMessage() {}

func (x *TableCell) ProtoReflect() protoreflect.Message {
	mi := &file_docling_v1_docling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableCell.ProtoReflect.Descriptor instead.
func (*TableCell) Descriptor() ([]byte, []int) {
	return file_docling_v1_docling_proto_rawDescGZIP(), []int{0}
}

func (x *TableCell) GetRowIndex() int32 {
	if x != nil {
		return x.RowIndex
	}
	return 0
}

func (x *TableCell) GetColIndex() int32 {
	if x != nil {
		return x.ColIndex
	}
	return 0
}

func (x *TableCell) GetRowSpan() int32 {
	if x != nil {
		return x.RowSpan
	}
	return 0
}

func (x *TableCell) GetColSpan() int32 {
	if x != nil {
		return x.ColSpan
	}
	return 0
}

func (x *TableCell) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TableCell) GetIsHeader() bool {
	if x != nil {
		return x.IsHeader
	}
	return false
}

// ParsedBlock is one logical block extracted from the document. The Go
// pipeline groups blocks into chunks before embedding.
type ParsedBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Type          BlockType              `protobuf:"varint,3,opt,name=type,proto3,enum=docling.v1.BlockType" json:"type,omitempty"`
	HeadingLevel  int32                  `protobuf:"varint,4,opt,name=heading_level,json=headingLevel,proto3" json:"heading_level,omitempty"`
	TableCells    []*TableCell           `protobuf:"bytes,5,rep,name=table_cells,json=tableCells,proto3" json:"table_cells,omitempty"`
	ImageCaption  string                 `protobuf:"bytes,6,opt,name=image_caption,json=imageCaption,proto3" json:"image_caption,omitempty"`
	PageNumber    int32                  `protobuf:"varint,7,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	Position      int32                  `protobuf:"varint,8,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedBlock) Reset() {
	*x = ParsedBlock{}
	mi := &file_docling_v1_docling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedBlock) ProtoMessage() {}

func (x *ParsedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_docling_v1_docling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedBlock.ProtoReflect.Descriptor instead.
func (*ParsedBlock) Descriptor() ([]byte, []int) {
	return file_docling_v1_docling_proto_rawDescGZIP(), []int{1}
}

func (x *ParsedBlock) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *ParsedBlock) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ParsedBlock) GetType() BlockType {
	if x != nil {
		return x.Type
	}
	return BlockType_BLOCK_TYPE_UNSPECIFIED
}

func (x *ParsedBlock) GetHeadingLevel() int32 {
	if x != nil {
		return x.HeadingLevel
	}
	return 0
}

func (x *ParsedBlock) GetTableCells() []*TableCell {
	if x != nil {
		return x.TableCells
	}
	return nil
}

func (x *ParsedBlock) GetImageCaption() string {
	if x != nil {
		return x.ImageCaption
	}
	return ""
}

func (x *ParsedBlock) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ParsedBlock) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

// DocumentStructure carries document-level metadata Docling extracts
// (title, author, language, page count, ...).
type DocumentStructure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	PageCount     int32                  `protobuf:"varint,4,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	OutlineMd     string                 `protobuf:"bytes,5,opt,name=outline_md,json=outlineMd,proto3" json:"outline_md,omitempty"` // Optional Markdown outline
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentStructure) Reset() {
	*x = DocumentStructure{}
	mi := &file_docling_v1_docling_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentStructure) ProtoMessage() {}

func (x *DocumentStructure) ProtoReflect() protoreflect.Message {
	mi := &file_docling_v1_docling_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentStructure.ProtoReflect.Descriptor instead.
func (*DocumentStructure) Descriptor() ([]byte, []int) {
	return file_docling_v1_docling_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentStructure) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentStructure) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *DocumentStructure) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *DocumentStructure) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *DocumentStructure) GetOutlineMd() string {
	if x != nil {
		return x.OutlineMd
	}
	return ""
}

func (x *DocumentStructure) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ParseDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseDocumentRequest) Reset() {
	*x = ParseDocumentRequest{}
	mi := &file_docling_v1_docling_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseDocumentRequest) ProtoMessage() {}

func (x *ParseDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docling_v1_docling_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseDocumentRequest.ProtoReflect.Descriptor instead.
func (*ParseDocumentRequest) Descriptor() ([]byte, []int) {
	return file_docling_v1_docling_proto_rawDescGZIP(), []int{3}
}

func (x *ParseDocumentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ParseDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ParseDocumentRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ParseDocumentRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ParseDocumentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ParseDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*ParsedBlock         `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	Structure     *DocumentStructure     `protobuf:"bytes,2,opt,name=structure,proto3" json:"structure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseDocumentResponse) Reset() {
	*x = ParseDocumentResponse{}
	mi := &file_docling_v1_docling_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseDocumentResponse) ProtoMessage() {}

func (x *ParseDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docling_v1_docling_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseDocumentResponse.ProtoReflect.Descriptor instead.
func (*ParseDocumentResponse) Descriptor() ([]byte, []int) {
	return file_docling_v1_docling_proto_rawDescGZIP(), []int{4}
}

func (x *ParseDocumentResponse) GetBlocks() []*ParsedBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *ParseDocumentResponse) GetStructure() *DocumentStructure {
	if x != nil {
		return x.Structure
	}
	return nil
}

var File_docling_v1_docling_proto protoreflect.FileDescriptor

const file_docling_v1_docling_proto_rawDesc = "" +
	"\n" +
	"\x18docling/v1/docling.proto\x12\n" +
	"docling.v1\"\xac\x01\n" +
	"\tTableCell\x12\x1b\n" +
	"\trow_index\x18\x01 \x01(\x05R\browIndex\x12\x1b\n" +
	"\tcol_index\x18\x02 \x01(\x05R\bcolIndex\x12\x19\n" +
	"\brow_span\x18\x03 \x01(\x05R\arowSpan\x12\x19\n" +
	"\bcol_span\x18\x04 \x01(\x05R\acolSpan\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x1b\n" +
	"\tis_header\x18\x06 \x01(\bR\bisHeader\"\xa6\x02\n" +
	"\vParsedBlock\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.docling.v1.BlockTypeR\x04type\x12#\n" +
	"\rheading_level\x18\x04 \x01(\x05R\fheadingLevel\x126\n" +
	"\vtable_cells\x18\x05 \x03(\v2\x15.docling.v1.TableCellR\n" +
	"tableCells\x12#\n" +
	"\rimage_caption\x18\x06 \x01(\tR\fimageCaption\x12\x1f\n" +
	"\vpage_number\x18\a \x01(\x05R\n" +
	"pageNumber\x12\x1a\n" +
	"\bposition\x18\b \x01(\x05R\bposition\"\xa1\x02\n" +
	"\x11DocumentStructure\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"page_count\x18\x04 \x01(\x05R\tpageCount\x12\x1d\n" +
	"\n" +
	"outline_md\x18\x05 \x01(\tR\toutlineMd\x12G\n" +
	"\bmetadata\x18\x06 \x03(\v2+.docling.v1.DocumentStructure.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x02\n" +
	"\x14ParseDocumentRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12J\n" +
	"\bmetadata\x18\x05 \x03(\v2..docling.v1.ParseDocumentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x01\n" +
	"\x15ParseDocumentResponse\x12/\n" +
	"\x06blocks\x18\x01 \x03(\v2\x17.docling.v1.ParsedBlockR\x06blocks\x12;\n" +
	"\tstructure\x18\x02 \x01(\v2\x1d.docling.v1.DocumentStructureR\tstructure*\xe6\x01\n" +
	"\tBlockType\x12\x1a\n" +
	"\x16BLOCK_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14BLOCK_TYPE_PARAGRAPH\x10\x01\x12\x16\n" +
	"\x12BLOCK_TYPE_HEADING\x10\x02\x12\x18\n" +
	"\x14BLOCK_TYPE_LIST_ITEM\x10\x03\x12\x14\n" +
	"\x10BLOCK_TYPE_TABLE\x10\x04\x12\x15\n" +
	"\x11BLOCK_TYPE_FIGURE\x10\x05\x12\x16\n" +
	"\x12BLOCK_TYPE_CAPTION\x10\x06\x12\x13\n" +
	"\x0fBLOCK_TYPE_CODE\x10\a\x12\x17\n" +
	"\x13BLOCK_TYPE_FOOTNOTE\x10\b2f\n" +
	"\x0eDoclingService\x12T\n" +
	"\rParseDocument\x12 .docling.v1.ParseDocumentRequest\x1a!.docling.v1.ParseDocumentResponseBBZ@github.com/kennguy3n/hunting-fishball/proto/docling/v1;doclingv1b\x06proto3"

var (
	file_docling_v1_docling_proto_rawDescOnce sync.Once
	file_docling_v1_docling_proto_rawDescData []byte
)

func file_docling_v1_docling_proto_rawDescGZIP() []byte {
	file_docling_v1_docling_proto_rawDescOnce.Do(func() {
		file_docling_v1_docling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docling_v1_docling_proto_rawDesc), len(file_docling_v1_docling_proto_rawDesc)))
	})
	return file_docling_v1_docling_proto_rawDescData
}

var file_docling_v1_docling_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_docling_v1_docling_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_docling_v1_docling_proto_goTypes = []any{
	(BlockType)(0),                // 0: docling.v1.BlockType
	(*TableCell)(nil),             // 1: docling.v1.TableCell
	(*ParsedBlock)(nil),           // 2: docling.v1.ParsedBlock
	(*DocumentStructure)(nil),     // 3: docling.v1.DocumentStructure
	(*ParseDocumentRequest)(nil),  // 4: docling.v1.ParseDocumentRequest
	(*ParseDocumentResponse)(nil), // 5: docling.v1.ParseDocumentResponse
	nil,                           // 6: docling.v1.DocumentStructure.MetadataEntry
	nil,                           // 7: docling.v1.ParseDocumentRequest.MetadataEntry
}
var file_docling_v1_docling_proto_depIdxs = []int32{
	0, // 0: docling.v1.ParsedBlock.type:type_name -> docling.v1.BlockType
	1, // 1: docling.v1.ParsedBlock.table_cells:type_name -> docling.v1.TableCell
	6, // 2: docling.v1.DocumentStructure.metadata:type_name -> docling.v1.DocumentStructure.MetadataEntry
	7, // 3: docling.v1.ParseDocumentRequest.metadata:type_name -> docling.v1.ParseDocumentRequest.MetadataEntry
	2, // 4: docling.v1.ParseDocumentResponse.blocks:type_name -> docling.v1.ParsedBlock
	3, // 5: docling.v1.ParseDocumentResponse.structure:type_name -> docling.v1.DocumentStructure
	4, // 6: docling.v1.DoclingService.ParseDocument:input_type -> docling.v1.ParseDocumentRequest
	5, // 7: docling.v1.DoclingService.ParseDocument:output_type -> docling.v1.ParseDocumentResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_docling_v1_docling_proto_init() }
func file_docling_v1_docling_proto_init() {
	if File_docling_v1_docling_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docling_v1_docling_proto_rawDesc), len(file_docling_v1_docling_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docling_v1_docling_proto_goTypes,
		DependencyIndexes: file_docling_v1_docling_proto_depIdxs,
		EnumInfos:         file_docling_v1_docling_proto_enumTypes,
		MessageInfos:      file_docling_v1_docling_proto_msgTypes,
	}.Build()
	File_docling_v1_docling_proto = out.File
	file_docling_v1_docling_proto_goTypes = nil
	file_docling_v1_docling_proto_depIdxs = nil
}
