// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: docling/v1/docling.proto

package doclingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DoclingService_ParseDocument_FullMethodName = "/docling.v1.DoclingService/ParseDocument"
)

// DoclingServiceClient is the client API for DoclingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DoclingService wraps the Python Docling document parser. The Go context
// engine calls ParseDocument from Stage 2 (Parse) of the ingestion
// pipeline.
type DoclingServiceClient interface {
	ParseDocument(ctx context.Context, in *ParseDocumentRequest, opts ...grpc.CallOption) (*ParseDocumentResponse, error)
}

type doclingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDoclingServiceClient(cc grpc.ClientConnInterface) DoclingServiceClient {
	return &doclingServiceClient{cc}
}

func (c *doclingServiceClient) ParseDocument(ctx context.Context, in *ParseDocumentRequest, opts ...grpc.CallOption) (*ParseDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseDocumentResponse)
	err := c.cc.Invoke(ctx, DoclingService_ParseDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoclingServiceServer is the server API for DoclingService service.
// All implementations must embed UnimplementedDoclingServiceServer
// for forward compatibility.
//
// DoclingService wraps the Python Docling document parser. The Go context
// engine calls ParseDocument from Stage 2 (Parse) of the ingestion
// pipeline.
type DoclingServiceServer interface {
	ParseDocument(context.Context, *ParseDocumentRequest) (*ParseDocumentResponse, error)
	mustEmbedUnimplementedDoclingServiceServer()
}

// UnimplementedDoclingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDoclingServiceServer struct{}

func (UnimplementedDoclingServiceServer) ParseDocument(context.Context, *ParseDocumentRequest) (*ParseDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseDocument not implemented")
}
func (UnimplementedDoclingServiceServer) mustEmbedUnimplementedDoclingServiceServer() {}
func (UnimplementedDoclingServiceServer) testEmbeddedByValue()                        {}

// UnsafeDoclingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DoclingServiceServer will
// result in compilation errors.
type UnsafeDoclingServiceServer interface {
	mustEmbedUnimplementedDoclingServiceServer()
}

func RegisterDoclingServiceServer(s grpc.ServiceRegistrar, srv DoclingServiceServer) {
	// If the following call panics, it indicates UnimplementedDoclingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DoclingService_ServiceDesc, srv)
}

func _DoclingService_ParseDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoclingServiceServer).ParseDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoclingService_ParseDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoclingServiceServer).ParseDocument(ctx, req.(*ParseDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DoclingService_ServiceDesc is the grpc.ServiceDesc for DoclingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DoclingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "docling.v1.DoclingService",
	HandlerType: (*DoclingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseDocument",
			Handler:    _DoclingService_ParseDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "docling/v1/docling.proto",
}
