// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: graphrag/v1/graphrag.proto

package graphragv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExtractRequest is one document's worth of chunks. tenant_id is
// forwarded for logging and quota enforcement; the extractor itself
// is stateless so cross-tenant pollution is structurally
// impossible.
type ExtractRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tenant_id of the calling pipeline. Required.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// document_id groups every node/edge produced from this request
	// — the coordinator deletes-then-writes by document_id so a
	// re-extraction supersedes prior nodes for the same document.
	DocumentId string `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	// chunks are the parsed text segments, in document order. The
	// extractor is allowed to span chunks when forming a relation
	// (e.g. "[Alice in chunk 1] WORKS_AT [Acme in chunk 2]") but
	// every node MUST point back to a single canonical chunk id.
	Chunks []*Chunk `protobuf:"bytes,3,rep,name=chunks,proto3" json:"chunks,omitempty"`
	// model_id selects a specific extractor model. Optional —
	// empty means "use the service default".
	ModelId       string `protobuf:"bytes,4,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_graphrag_v1_graphrag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphrag_v1_graphrag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_graphrag_v1_graphrag_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ExtractRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ExtractRequest) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *ExtractRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type Chunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chunk_id is the canonical id minted by the parsing stage.
	ChunkId string `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	// text is the chunk content the extractor sees. The service
	// does not store this verbatim — only the derived nodes/edges
	// leave the call.
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_graphrag_v1_graphrag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_graphrag_v1_graphrag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_graphrag_v1_graphrag_proto_rawDescGZIP(), []int{1}
}

func (x *Chunk) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *Chunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Node is one extracted entity. mentions[] points to chunk_ids the
// node was observed in.
type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is a stable identifier for this entity within the document.
	// The extractor mints it; common implementations hash the
	// canonical name. Required.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// label is the entity type (e.g. "Person", "Organization",
	// "Project"). Required.
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// name is the canonical surface form ("Alice Smith"). Required.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// mentions lists the chunk_ids the node was observed in.
	Mentions []string `protobuf:"bytes,4,rep,name=mentions,proto3" json:"mentions,omitempty"`
	// properties carries extractor-specific metadata
	// (confidence, source_offsets, etc.) as primitive JSON values.
	// Servers MUST limit value size — a single property MUST NOT
	// exceed 4 KiB.
	Properties    map[string]string `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_graphrag_v1_graphrag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_graphrag_v1_graphrag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_graphrag_v1_graphrag_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetMentions() []string {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *Node) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type Edge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// source_id and destination_id reference Node.id values from the
	// same response.
	SourceId      string `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	DestinationId string `protobuf:"bytes,2,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	// relation is the relationship type (e.g. "WORKS_AT", "MENTIONS").
	// Required.
	Relation string `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	// confidence in [0, 1] is optional; 0 means unknown.
	Confidence float32 `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// properties carries extra metadata (e.g. evidence_chunk_id).
	Properties    map[string]string `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_graphrag_v1_graphrag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_graphrag_v1_graphrag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_graphrag_v1_graphrag_proto_rawDescGZIP(), []int{3}
}

func (x *Edge) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Edge) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

func (x *Edge) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *Edge) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Edge) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type ExtractResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Nodes []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges []*Edge                `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	// model_id echoes the model used for traceability.
	ModelId       string `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_graphrag_v1_graphrag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graphrag_v1_graphrag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_graphrag_v1_graphrag_proto_rawDescGZIP(), []int{4}
}

func (x *ExtractResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ExtractResponse) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *ExtractResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

var File_graphrag_v1_graphrag_proto protoreflect.FileDescriptor

const file_graphrag_v1_graphrag_proto_rawDesc = "" +
	"\n" +
	"\x1agraphrag/v1/graphrag.proto\x12\vgraphrag.v1\"\x95\x01\n" +
	"\x0eExtractRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12*\n" +
	"\x06chunks\x18\x03 \x03(\v2\x12.graphrag.v1.ChunkR\x06chunks\x12\x19\n" +
	"\bmodel_id\x18\x04 \x01(\tR\amodelId\"6\n" +
	"\x05Chunk\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\xde\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bmentions\x18\x04 \x03(\tR\bmentions\x12A\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2!.graphrag.v1.Node.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x02\n" +
	"\x04Edge\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12%\n" +
	"\x0edestination_id\x18\x02 \x01(\tR\rdestinationId\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\x12A\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2!.graphrag.v1.Edge.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"~\n" +
	"\x0fExtractResponse\x12'\n" +
	"\x05nodes\x18\x01 \x03(\v2\x11.graphrag.v1.NodeR\x05nodes\x12'\n" +
	"\x05edges\x18\x02 \x03(\v2\x11.graphrag.v1.EdgeR\x05edges\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId2_\n" +
	"\x0fGraphRAGService\x12L\n" +
	"\x0fExtractEntities\x12\x1b.graphrag.v1.ExtractRequest\x1a\x1c.graphrag.v1.ExtractResponseBDZBgithub.com/kennguy3n/hunting-fishball/proto/graphrag/v1;graphragv1b\x06proto3"

var (
	file_graphrag_v1_graphrag_proto_rawDescOnce sync.Once
	file_graphrag_v1_graphrag_proto_rawDescData []byte
)

func file_graphrag_v1_graphrag_proto_rawDescGZIP() []byte {
	file_graphrag_v1_graphrag_proto_rawDescOnce.Do(func() {
		file_graphrag_v1_graphrag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graphrag_v1_graphrag_proto_rawDesc), len(file_graphrag_v1_graphrag_proto_rawDesc)))
	})
	return file_graphrag_v1_graphrag_proto_rawDescData
}

var file_graphrag_v1_graphrag_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_graphrag_v1_graphrag_proto_goTypes = []any{
	(*ExtractRequest)(nil),  // 0: graphrag.v1.ExtractRequest
	(*Chunk)(nil),           // 1: graphrag.v1.Chunk
	(*Node)(nil),            // 2: graphrag.v1.Node
	(*Edge)(nil),            // 3: graphrag.v1.Edge
	(*ExtractResponse)(nil), // 4: graphrag.v1.ExtractResponse
	nil,                     // 5: graphrag.v1.Node.PropertiesEntry
	nil,                     // 6: graphrag.v1.Edge.PropertiesEntry
}
var file_graphrag_v1_graphrag_proto_depIdxs = []int32{
	1, // 0: graphrag.v1.ExtractRequest.chunks:type_name -> graphrag.v1.Chunk
	5, // 1: graphrag.v1.Node.properties:type_name -> graphrag.v1.Node.PropertiesEntry
	6, // 2: graphrag.v1.Edge.properties:type_name -> graphrag.v1.Edge.PropertiesEntry
	2, // 3: graphrag.v1.ExtractResponse.nodes:type_name -> graphrag.v1.Node
	3, // 4: graphrag.v1.ExtractResponse.edges:type_name -> graphrag.v1.Edge
	0, // 5: graphrag.v1.GraphRAGService.ExtractEntities:input_type -> graphrag.v1.ExtractRequest
	4, // 6: graphrag.v1.GraphRAGService.ExtractEntities:output_type -> graphrag.v1.ExtractResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_graphrag_v1_graphrag_proto_init() }
func file_graphrag_v1_graphrag_proto_init() {
	if File_graphrag_v1_graphrag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graphrag_v1_graphrag_proto_rawDesc), len(file_graphrag_v1_graphrag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graphrag_v1_graphrag_proto_goTypes,
		DependencyIndexes: file_graphrag_v1_graphrag_proto_depIdxs,
		MessageInfos:      file_graphrag_v1_graphrag_proto_msgTypes,
	}.Build()
	File_graphrag_v1_graphrag_proto = out.File
	file_graphrag_v1_graphrag_proto_goTypes = nil
	file_graphrag_v1_graphrag_proto_depIdxs = nil
}
