// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: graphrag/v1/graphrag.proto

package graphragv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GraphRAGService_ExtractEntities_FullMethodName = "/graphrag.v1.GraphRAGService/ExtractEntities"
)

// GraphRAGServiceClient is the client API for GraphRAGService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GraphRAGService extracts named entities and the relations between
// them from chunked documents. Stage 3b of the ingestion pipeline
// (after Stage 3 Embed, before Stage 4 Store) calls
// ExtractEntities to derive nodes and edges, which the coordinator
// writes to the per-tenant FalkorDB graph for traversal-aided
// retrieval. See docs/ARCHITECTURE.md §3.3 "Pipeline coordinator".
type GraphRAGServiceClient interface {
	ExtractEntities(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
}

type graphRAGServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphRAGServiceClient(cc grpc.ClientConnInterface) GraphRAGServiceClient {
	return &graphRAGServiceClient{cc}
}

func (c *graphRAGServiceClient) ExtractEntities(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractResponse)
	err := c.cc.Invoke(ctx, GraphRAGService_ExtractEntities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraphRAGServiceServer is the server API for GraphRAGService service.
// All implementations must embed UnimplementedGraphRAGServiceServer
// for forward compatibility.
//
// GraphRAGService extracts named entities and the relations between
// them from chunked documents. Stage 3b of the ingestion pipeline
// (after Stage 3 Embed, before Stage 4 Store) calls
// ExtractEntities to derive nodes and edges, which the coordinator
// writes to the per-tenant FalkorDB graph for traversal-aided
// retrieval. See docs/ARCHITECTURE.md §3.3 "Pipeline coordinator".
type GraphRAGServiceServer interface {
	ExtractEntities(context.Context, *ExtractRequest) (*ExtractResponse, error)
	mustEmbedUnimplementedGraphRAGServiceServer()
}

// UnimplementedGraphRAGServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraphRAGServiceServer struct{}

func (UnimplementedGraphRAGServiceServer) ExtractEntities(context.Context, *ExtractRequest) (*ExtractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractEntities not implemented")
}
func (UnimplementedGraphRAGServiceServer) mustEmbedUnimplementedGraphRAGServiceServer() {}
func (UnimplementedGraphRAGServiceServer) testEmbeddedByValue()                         {}

// UnsafeGraphRAGServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraphRAGServiceServer will
// result in compilation errors.
type UnsafeGraphRAGServiceServer interface {
	mustEmbedUnimplementedGraphRAGServiceServer()
}

func RegisterGraphRAGServiceServer(s grpc.ServiceRegistrar, srv GraphRAGServiceServer) {
	// If the following call panics, it indicates UnimplementedGraphRAGServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraphRAGService_ServiceDesc, srv)
}

func _GraphRAGService_ExtractEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphRAGServiceServer).ExtractEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphRAGService_ExtractEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphRAGServiceServer).ExtractEntities(ctx, req.(*ExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GraphRAGService_ServiceDesc is the grpc.ServiceDesc for GraphRAGService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraphRAGService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graphrag.v1.GraphRAGService",
	HandlerType: (*GraphRAGServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExtractEntities",
			Handler:    _GraphRAGService_ExtractEntities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "graphrag/v1/graphrag.proto",
}
