// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: embedding/v1/embedding.proto

package embeddingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComputeEmbeddingsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Chunks   []string               `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	// model_id selects a specific model. Optional — empty means "use the
	// tenant default", which the embedding service resolves from its own
	// config map.
	ModelId       string `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeEmbeddingsRequest) Reset() {
	*x = ComputeEmbeddingsRequest{}
	mi := &file_embedding_v1_embedding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeEmbeddingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeEmbeddingsRequest) ProtoMessage() {}

func (x *ComputeEmbeddingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_v1_embedding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeEmbeddingsRequest.ProtoReflect.Descriptor instead.
func (*ComputeEmbeddingsRequest) Descriptor() ([]byte, []int) {
	return file_embedding_v1_embedding_proto_rawDescGZIP(), []int{0}
}

func (x *ComputeEmbeddingsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ComputeEmbeddingsRequest) GetChunks() []string {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *ComputeEmbeddingsRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type Embedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	mi := &file_embedding_v1_embedding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_v1_embedding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_embedding_v1_embedding_proto_rawDescGZIP(), []int{1}
}

func (x *Embedding) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type ComputeEmbeddingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*Embedding           `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Dimensions    int32                  `protobuf:"varint,3,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeEmbeddingsResponse) Reset() {
	*x = ComputeEmbeddingsResponse{}
	mi := &file_embedding_v1_embedding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeEmbeddingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeEmbeddingsResponse) ProtoMessage() {}

func (x *ComputeEmbeddingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_v1_embedding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeEmbeddingsResponse.ProtoReflect.Descriptor instead.
func (*ComputeEmbeddingsResponse) Descriptor() ([]byte, []int) {
	return file_embedding_v1_embedding_proto_rawDescGZIP(), []int{2}
}

func (x *ComputeEmbeddingsResponse) GetEmbeddings() []*Embedding {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

func (x *ComputeEmbeddingsResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ComputeEmbeddingsResponse) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

var File_embedding_v1_embedding_proto protoreflect.FileDescriptor

const file_embedding_v1_embedding_proto_rawDesc = "" +
	"\n" +
	"\x1cembedding/v1/embedding.proto\x12\fembedding.v1\"j\n" +
	"\x18ComputeEmbeddingsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06chunks\x18\x02 \x03(\tR\x06chunks\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\"#\n" +
	"\tEmbedding\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"\x8f\x01\n" +
	"\x19ComputeEmbeddingsResponse\x127\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\x17.embedding.v1.EmbeddingR\n" +
	"embeddings\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x03 \x01(\x05R\n" +
	"dimensions2x\n" +
	"\x10EmbeddingService\x12d\n" +
	"\x11ComputeEmbeddings\x12&.embedding.v1.ComputeEmbeddingsRequest\x1a'.embedding.v1.ComputeEmbeddingsResponseBFZDgithub.com/kennguy3n/hunting-fishball/proto/embedding/v1;embeddingv1b\x06proto3"

var (
	file_embedding_v1_embedding_proto_rawDescOnce sync.Once
	file_embedding_v1_embedding_proto_rawDescData []byte
)

func file_embedding_v1_embedding_proto_rawDescGZIP() []byte {
	file_embedding_v1_embedding_proto_rawDescOnce.Do(func() {
		file_embedding_v1_embedding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_embedding_v1_embedding_proto_rawDesc), len(file_embedding_v1_embedding_proto_rawDesc)))
	})
	return file_embedding_v1_embedding_proto_rawDescData
}

var file_embedding_v1_embedding_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_embedding_v1_embedding_proto_goTypes = []any{
	(*ComputeEmbeddingsRequest)(nil),  // 0: embedding.v1.ComputeEmbeddingsRequest
	(*Embedding)(nil),                 // 1: embedding.v1.Embedding
	(*ComputeEmbeddingsResponse)(nil), // 2: embedding.v1.ComputeEmbeddingsResponse
}
var file_embedding_v1_embedding_proto_depIdxs = []int32{
	1, // 0: embedding.v1.ComputeEmbeddingsResponse.embeddings:type_name -> embedding.v1.Embedding
	0, // 1: embedding.v1.EmbeddingService.ComputeEmbeddings:input_type -> embedding.v1.ComputeEmbeddingsRequest
	2, // 2: embedding.v1.EmbeddingService.ComputeEmbeddings:output_type -> embedding.v1.ComputeEmbeddingsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_embedding_v1_embedding_proto_init() }
func file_embedding_v1_embedding_proto_init() {
	if File_embedding_v1_embedding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_embedding_v1_embedding_proto_rawDesc), len(file_embedding_v1_embedding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_embedding_v1_embedding_proto_goTypes,
		DependencyIndexes: file_embedding_v1_embedding_proto_depIdxs,
		MessageInfos:      file_embedding_v1_embedding_proto_msgTypes,
	}.Build()
	File_embedding_v1_embedding_proto = out.File
	file_embedding_v1_embedding_proto_goTypes = nil
	file_embedding_v1_embedding_proto_depIdxs = nil
}
